### ISSUE TITLE
:compact Option Appears Broken

### ISSUE THREAD

**Issue by jleffert** [radar/distance_of_time_in_words#123]
I get the error 

`Unknown key: :compact. Valid keys are: :words_connector, :two_words_connector, :last_word_connector, :locale`

When calling

`distance_of_time_in_words(Time.current, Time.current + 10.minutes, include_seconds: true, compact: true)`

I'm pretty sure the param is no longer getting deleted properly here:

`DOTIW::Methods#options_with_scope
`
![image](https://user-images.githubusercontent.com/3392915/112547623-f925ba00-8d88-11eb-9774-f7447a5edd3b.png)

**Comment by rposborne** [comment]
Confirming this,   Looks like the compact functionality doesn't have great coverage over it only its use with `distance_of_time`  is tested.
