### ISSUE TITLE
Not calculating days properly

### ISSUE THREAD

**Issue by jonathansimmons** [radar/distance_of_time_in_words#31]
I am using distance_of_time_in_words with the expanded gem as follows:

`<%= distance_of_time_in_words(@client.report_missing_after.days, Date.today, false, except: ["hours","minutes"])  %>`
If @client.report_missing_after were to equal 7 the code above would return "7 Days" as expected. This works fine for if `@client.report_missing_after` equals 1-28, when I reach 29 sudenly the output looks like: `87847649280000 years and 238878720000 days` which is not correct.

I can't figure out where I'm going wrong here. Help?

UPDATE

I have also tried to pass first argument as an intergerand it still doesn't work:

`<%= distance_of_time_in_words(29.days ,0, false, except: ["hours","minutes"]) %>`

**Comment by radar** [comment]
@jonathansimmons Is this still an issue?

**Comment by DavidVII** [comment]
@radar I discovered this issue today.

Consider the following:

```
>> distance_of_time_in_words(Time.zone.now, Time.zone.now + 1.day - 1.minute)
=> "23 hours and 59 minutes"
>> distance_of_time_in_words(Time.zone.now, Time.zone.now + 15.days - 1.minute)
=> "14 days, 23 hours, and 59 minutes"
>> distance_of_time_in_words(Time.zone.now, Time.zone.now + 28.days - 1.minute)
=> "27 days, 23 hours, and 59 minutes"
>> distance_of_time_in_words(Time.zone.now, Time.zone.now + 29.days - 1.minute)
=> "29 days, 23 hours, and 59 minutes”
```

everything works as expected until you hit the `+ 29.days` line. 1-28 work as expected.

**Comment by DavidVII** [comment]
Looks like it could be related to this: https://github.com/radar/dotiw/blob/master/lib/dotiw/time_hash.rb#L51

**Comment by radar** [comment]
But how long is a month?

**Comment by lauranjansen** [comment]
I think I fixed this as part of my weeks implementation. Can you verify this isn't an issue anymore?

**Comment by dblock** [comment]
This is fixed. Added tests confirming in https://github.com/radar/distance_of_time_in_words/pull/105/commits/b4a601bc36c609e9d4615abec0582ed322851448.
