### ISSUE TITLE
not working with DateTime

### ISSUE THREAD

**Issue by Olefine** [radar/distance_of_time_in_words#59]
Original distance_of_time_in_words working with DateTime and Time object. But your helper works only with Time. If i try use it with DateTime, i am getting this error

```
 undefined method `dst?' for Wed, 17 Jun 2015 15:16:31 +0300:DateTime
```

I can use this, but all AR timestamps are DateTime and it looks very ugly 

```
Time.at(DateTime.now)
```

**Comment by radar** [comment]
Steps to reproduce in a new app please.

**Comment by Olefine** [comment]
@radar  
```
  distance_of_time_in_words(DateTime.now, object.end_date)
```

end_date is datetime type

**Comment by radar** [comment]
Can you please show me a stacktrace for this issue too?

**Comment by redbar0n** [comment]
It works for me.
```
> distance_of_time_in_words(DateTime.now, DateTime.now-2.days)
=> "1 day, 23 hours, and 59 minutes"
```

**Comment by dblock** [comment]
Added tests confirming this works in https://github.com/dblock/distance_of_time_in_words/commit/734c2fb06c643cde5692a25bed17fe65e4f22b69.

**Comment by dblock** [comment]
Note that this was probably failing in the past because `TimeHash` calls `dst?`, but `DateTime` does not implement that. The implementation of `distance_of_time_in_words_hash` now calls `to_time` on anything that's not a `Time`.
