### ISSUE TITLE
Difference in just hours

### ISSUE THREAD

**Issue by alfie-max** [radar/distance_of_time_in_words#74]
I expected the code 
`distance_of_time_in_words(Date.new(2015), Date.today, only: :hours)`
To return me something like x hours, i.e total number of hours. between the two dates
Instead it gave me just the hours part in the difference, i.e something like `11 hours`

**Comment by alfie-max** [comment]
I agree the documentation makes this clear, but wouldn't it be more intuitive if it just returned the difference in hours.
Just suggesting like maybe a new feature or something.

**Comment by lauranjansen** [comment]
Try using it in combination with :accumulate_on => :hours, that should give you what you're looking for.

**Comment by alfie-max** [comment]
@lauranjansen thanks, that works. Maybe an example case could be shown in the README for future reference.

**Comment by dblock** [comment]
README documents `accumulate_on`
