### ISSUE TITLE
negative number of weeks (-1) returned

### ISSUE THREAD

**Issue by aphilippi** [radar/distance_of_time_in_words#75]
The following call returns a weird result:

distance_of_time_in_words(Date.parse('31.03.2015').to_time, Time.parse('01.03.2016'))
"11 months, -1 weeks, and 6 days"

**Comment by lauranjansen** [comment]
Thanks for reporting, I was able to reproduce it and added a failing test case for it. Looking into fixing this.

**Comment by aphilippi** [comment]
+1 :)

**Comment by dblock** [comment]
This is still an issue, maybe someone wants to take a stab at fixing it? 
https://github.com/dblock/distance_of_time_in_words/commit/1f12d1c20a15fa57cdc1b281f1ae69463b6cc4e9

**Comment by dblock** [comment]
There was an attempt of a fix in https://github.com/radar/distance_of_time_in_words/pull/82.
