### ISSUE TITLE
Totally random result?

### ISSUE THREAD

**Issue by bovender** [radar/distance_of_time_in_words#81]
Between January 31 and March 1 there should be exactly 1 month, or 1 month and 1 day if considering distance rather than interval, but I get this:

    irb(main):008:0> distance_of_time_in_words(Date.new(2014,1,31), Date.new(2014,3,1), locale: :en)
    => "1 month, -1 weeks, and 5 days"

This seems totally off. What's going on?

**Comment by ivanovaleksey** [comment]
Standard Rails `distance_of_time_in_words ` gives me `29 days`, not "exactly 1 month".

**Comment by bovender** [comment]
You're right of course. My point however was not so much to compare the output with the default implementation, but to investigate why it says *minus* 1 week *plus* 5 days.

**Comment by ivanovaleksey** [comment]
Yes, I see. I forgot to and "FYI" ☺️. I will try to debug this case, maybe there is some bug here. 
But I am not sure if I can find something.

**Comment by ivanovaleksey** [comment]
@bovender could please check #82 ? It looks very ugly but it seems like it fixes your case.

**Comment by dblock** [comment]
This is a dup of #75.
