### ISSUE TITLE
Alters the default behavior of distance_of_time_in_words_to_now

### ISSUE THREAD

**Issue by aldent95** [radar/distance_of_time_in_words#85]
Just started using this and it does exactly what I need for my project, except for one thing.

The default distance_of_time_in_words_to_now would throw an error when passed nil, allowing me to rescue and provide Never to my view.

However, with this gem, it seems to default to Time.now and gives less than 1 second instead of an error.

My Code, the values in the flights hash is pulled from my database and everything except pilotname can be nil if the user has not done a flight on that network, otherwise, they are Time objects.

    <% @flights.each do |flights| %>

        <tr class="js-datatable-data">

          <td><%=flights[:pilotname] %></td>

          <td><%= distance_of_time_in_words_to_now(flights[:vastim], {:only =>:days, :accumulate_on => :days}) + ' ago' rescue 'Never' %></td>

          <td><%= distance_of_time_in_words_to_now(flights[:pilotedge], {:only =>:days, :accumulate_on => :days})  + ' ago' rescue 'Never' %></td>

          <td><%= distance_of_time_in_words_to_now(flights[:ivao], {:only =>:days, :accumulate_on => :days})  + ' ago' rescue 'Never' %></td>

          <td><%= distance_of_time_in_words_to_now(flights[:offline], {:only =>:days, :accumulate_on => :days})  + ' ago' rescue 'Never' %></td>
        </tr>

    <% end %>

And the result is this table
Pilot              | VATSIM                     | PilotEdge                  | IVAO                         | Offline
Alex2Dent2   | less than 1 day ago  | less than 1 day ago  | less than 1 day ago  | less than 1 day ago
Alex3Dent3   | less than 1 day ago  | less than 1 day ago  | less than 1 day ago  | less than 1 day ago
AlexDent       | less than 1 day ago  | less than 1 day ago  | less than 1 day ago  | 48 days ago

Now I know and can just do a nilcheck to get around the issue and that's exactly what I will be doing but it is probably worth checking into this issue so that people don't get weird things happening when they switch to using this gem.

EDIT: Yes I meant nil instead of null. That's what I get for working in C# during the day at work and Ruby in my own projects -_-

**Comment by lauranjansen** [comment]
Hi @aldent95, I just looked into this and it does seem like the default behaviour of `distance_of_time_in_words_to_now` (which should just be an alias for `distance_of_time_in_words`) is different when this gem is used.

#Without `dotiw` installed
```helper.distance_of_time_in_words(nil)
ArgumentError: nil can't be converted to a Time value```
```helper.distance_of_time_in_words_to_now(nil)
ArgumentError: nil can't be converted to a Time value```

#With `dotiw` installed
```helper.distance_of_time_in_words(nil)
NoMethodError: undefined method `seconds' for nil:NilClass```
```helper.distance_of_time_in_words_to_now(nil) => "less than 1 second"```

Would just using `distance_of_time_in_words(nil)` work for you? It defaults to comparing with now anyway.

**Comment by dblock** [comment]
Feels like we should document this behavior as a gotcha?

**Comment by dblock** [comment]
@joshuapinter any ideas about this after #117 ?

**Comment by joshuapinter** [comment]
@dblock Yes. With the implementation of `distance_of_time_in_words_to_now` in #117, this returns an error when `nil` is passed, like the original method does. It's not the exact same error but it matches what is found in `distance_of_time_in_words`.

## Before #117

```ruby
$ distance_of_time_in_words_to_now( nil )
#=> "less than 1 second"

```

## After #117

```ruby
$ distance_of_time_in_words_to_now( nil )
#=> NoMethodError: undefined method `seconds' for nil:NilClass
```

So OP's issue, as described, is now resolved with #117.

**Comment by dblock** [comment]
I think we want to match the `ArgumentError` that you'd get without dotiw, would take a PR.

**Comment by joshuapinter** [comment]
I'll leave this up to @aldent95 to tackle.

**Comment by joshuapinter** [comment]
@dblock I had some extra downtime so I wrote up a PR to return the same `ArgumentError` that the original `distance_of_time_in_words` does. 

This works for all the typical methods. 

Capture in PR #118. Take a look when you get a chance.

**Comment by dblock** [comment]
Thanks @joshuapinter !

**Comment by joshuapinter** [comment]
👍
