### ISSUE TITLE
Release notes for 4.0?

### ISSUE THREAD

**Issue by monfresh** [radar/distance_of_time_in_words#86]
Hello. I noticed 4.0.0 was recently released, and I wanted to check out the release notes to find out if there are any breaking changes, but I couldn't find any in the Changelog or in the releases page in this repo. Could you please update the Changelog and mention whether or not there are any breaking changes. If there are, could you please provide documentation on how to upgrade? Thanks!

**Comment by barrywoolgar** [comment]
Here's the [version diff](https://github.com/radar/dotiw/compare/3be9d26...master). Looks to be adding support for Rails 5.1, and loss of support for Ruby 1.9.3.

**Comment by radar** [comment]
What @barrywoolgar said.
