### ISSUE TITLE
Totally weird behavior 

### ISSUE THREAD

**Issue by rabnawaz63** [radar/distance_of_time_in_words#96]
dotiw totally gives wrong results when i try to find distance within month (1 - 27 days) otherwise it works fine.
Here's an example.
`> distance_of_time_in_words(Date.today, Date.today - 2.days)
 => '14929920000 days' `

**Comment by lauranjansen** [comment]
Hi! I’m pretty sure the weird result in this case is caused by trying to calculate the distance with a date in the past. Granted, we should probably make sure to take the modulus before we do any calculations anyway.

**Comment by rabnawaz63** [comment]
@lauranjansen Yes i'm calculating the distance with a date in the past.

**Comment by lauranjansen** [comment]
I might be wrong (it’s been a while), but I think the intended use is to put the past date in the first argument and in your case Date.today in the second one.

**Comment by rabnawaz63** [comment]
@lauranjansen It gives the same result no matter where i put the past date. Is this is a bug in gem or i'm doing something wrong.

**Comment by lauranjansen** [comment]
Hey @rabnawaz63, do you still have this problem? I don't think the code base has changed, but when I run the same command I get the correct output:

`distance_of_time_in_words(Date.today, Date.today - 2.days) => "2 days"`
`distance_of_time_in_words(Date.today - 2.days, Date.today) => "2 days"`

**Comment by dblock** [comment]
This works as expected now, added tests in https://github.com/dblock/distance_of_time_in_words/commit/01fc1cb488c56ec705f707c4cbbac8a2f7753df6.
