### ISSUE TITLE
Guidance on using with pure ruby

### ISSUE THREAD

**Issue by meesern** [radar/distance_of_time_in_words#98]
Would be great if the readme included a section on use without rails.

**Comment by dblock** [comment]
Currently requires this workaround:

```ruby
module ActionView
  module Helpers
    module DateHelper
      def distance_of_time_in_words
      end

      def time_ago_in_words
      end
    end
  end
end

require 'dotiw/action_view_ext/helpers/date_helper.rb'
```

Then

```ruby
include  ActionView::Helpers::DateHelper

time_ago_in_words(...)
```

I'd like to fix this, @radar - want to (re)enable (Travis-)CI and I'll fix all this up?

**Comment by dblock** [comment]
To extend `Time`, above plus:

```ruby
class Time
  include ActionView::Helpers::DateHelper

  def ago_in_words(options = {})
    time_ago_in_words(self, options) + ' ago'
  end
end
```

**Comment by dblock** [comment]
https://github.com/dblock/slack-sup/pull/80

Brings in action_pack and action_view which we don't want.

**Comment by dblock** [comment]
https://github.com/radar/distance_of_time_in_words/pull/103
